"""Produce the admission evidence a compiled R0 dataset must carry.

Every check and every capability certificate is generated by a verification that
reads the actual artifacts, and records the hashes it was verified against, so a
reviewer can re-run the same check on the same bytes. Nothing here copies
capability names into a "passed" field.

Binding recorded on every evidence record:
  raw_capture_sha256   the raw native stream the samples came from
  raw_report_sha256    its capture report
  bundle_manifest_sha  the production bundle the capture was taken with
  capture_code_sha256  the capture entry that produced the stream
  contract_sha256      the current R0 interface contract
  dataset_manifest_sha the manifest being certified
  verification_scope   what was and was not verified
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tempfile
from collections import Counter, defaultdict
from pathlib import Path

from training_r0.config import DECISION_TICKS, ModelConfig
from training_r0.catalog import CardVocabulary
from training_r0.elite_tensorizer import REQUIRED_CAPTURE
from training_r0.il_dataset import load_sequence
from training_r0.model import R0Policy
from .prepare_600k import atomic_json, digest
from .r0_admission import current_contract, require_batch, require_dataset_files, require_manifest

CHECKS = ('source_hashes', 'native_identity', 'ruleset_resolved', 'opening_cycle_compatible',
          'tick_zero_capture', 'continuous_frames', 'continuous_events', 'entity_generation_identity',
          'public_information_only', 'feature_applicability_and_known_masks', 'legal_candidate_alignment',
          'rejected_action_loss_masks', 'action_offsets', 'sequence_boundaries', 'battle_level_split',
          'shard_readback', 'strict_r0_forward')
# Checks this module derives from artifacts, versus checks the compiler still
# asserts about its own labels. The distinction is recorded so a reviewer is never
# told a verification happened when it did not.
VERIFIED_BY_CERTIFY = ('source_hashes', 'native_identity', 'ruleset_resolved', 'tick_zero_capture',
                       'continuous_frames', 'continuous_events', 'entity_generation_identity',
                       'public_information_only', 'feature_applicability_and_known_masks',
                       'opening_cycle_compatible', 'sequence_boundaries', 'strict_r0_forward',
                       'legal_candidate_alignment', 'rejected_action_loss_masks', 'action_offsets',
                       'battle_level_split', 'shard_readback')


def stream_facts(capture_dir: Path) -> dict:
    """Derive continuity, identity and lineage facts from the raw stream."""
    from training_r0.replay_adapter import raw_capture_lines
    capture_dir = Path(capture_dir).resolve()
    raw = capture_dir / 'native-frames.jsonl.zst'
    report = json.loads((capture_dir / 'report.json').read_text(encoding='utf-8'))
    episode = None
    ticks = []
    damage_sequence = {}
    damage_gaps = []
    lifecycle_last = 0
    lifecycle_gaps = []
    lifecycle_rejected = 0
    lifecycle_null_id = 0
    telemetry_gaps = 0
    generations = defaultdict(set)
    event_kinds = defaultdict(set)
    duplicate_registrations = Counter()
    lineage = {}          # key -> whether ANY registration carried native lineage
    lineage_events = {}   # key -> first registration, for reporting
    damage_sources = {}   # source key -> total effective damage
    with raw_capture_lines(raw) as lines:
        for line in lines:
            row = json.loads(line)
            kind = row.get('kind')
            if kind == 'episode':
                episode = row
                continue
            if kind != 'frame':
                continue
            state = row['state']
            ticks.append(state['tick'])
            telemetry = row.get('telemetry') or {}
            if telemetry.get('gap'):
                telemetry_gaps += 1
            for event in telemetry.get('events') or ():
                epoch = telemetry.get('epoch')
                previous = damage_sequence.get(epoch)
                if previous is not None and event['sequence'] != previous + 1:
                    damage_gaps.append({'epoch': epoch, 'previous': previous, 'next': event['sequence']})
                damage_sequence[epoch] = event['sequence']
                source = event.get('attacker_key', event.get('source_key'))
                if source is not None:
                    damage_sources[source] = damage_sources.get(source, 0) + float(event.get('effective_damage') or 0)
            lifecycle = telemetry.get('lifecycle') or {}
            if lifecycle.get('gap'):
                lifecycle_gaps.append(state['tick'])
            lifecycle_rejected += int(lifecycle.get('rejected') or 0)
            lifecycle_null_id += int(lifecycle.get('null_id_removals') or 0)
            for event in lifecycle.get('events') or ():
                sequence = int(event['sequence'])
                if sequence != lifecycle_last + 1:
                    lifecycle_gaps.append({'previous': lifecycle_last, 'next': sequence})
                lifecycle_last = sequence
                if event['operation'] != 1:
                    continue
                key = event['key']
                # A generation key identifies an entity by side and native data id.
                # The native kind code can legitimately change between the pending
                # and live registration of the same object in one Tick, so it is
                # not part of the identity; those changes are counted separately.
                generations[key].add((event['side'], event['native_data_id']))
                event_kinds[key].add((event['side'], event['kind'], event['native_data_id']))
                duplicate_registrations[key] += 1
                # The pending->live registration repeats an entity without its
                # command context, so lineage is judged per entity, not per event.
                explained = bool(event.get('parent_key') or event.get('command_sequence')
                                 or (event.get('context_caller') and event.get('context_key')))
                lineage_events.setdefault(key, event)
                lineage[key] = lineage.get(key, False) or explained
    units_without_lineage = [{'key': key, 'tick': lineage_events[key]['tick']}
                             for key, ok in lineage.items() if not ok and key >= 5000000]
    effects_without_lineage = [{'key': key, 'tick': lineage_events[key]['tick']}
                               for key, ok in lineage.items() if not ok and 3000000 <= key < 5000000]
    if episode is None:
        raise ValueError('raw capture has no episode record')
    if not ticks:
        raise ValueError('raw capture has no frames')
    processing = capture_dir / 'processing-input.json'
    return dict(
        capture_dir=str(capture_dir), raw_sha256=digest(raw), raw_bytes=raw.stat().st_size,
        report=report, report_sha256=digest(capture_dir / 'report.json'),
        plan_sha256=digest(capture_dir / 'plan.json') if (capture_dir / 'plan.json').is_file() else None,
        processing_sha256=digest(processing) if processing.is_file() else None,
        processing=json.loads(processing.read_text(encoding='utf-8')) if processing.is_file() else None,
        episode=episode, bundle=episode.get('runtime_bundle') or {}, identity=episode.get('identity') or {},
        first_tick=ticks[0], last_tick=ticks[-1], frame_count=len(ticks),
        # A post-command resample legitimately repeats a Tick; only a regression or
        # a jump breaks frame continuity.
        frame_gaps=sum(1 for a, b in zip(ticks, ticks[1:]) if b != a and b != a + 1),
        repeated_ticks=sum(1 for a, b in zip(ticks, ticks[1:]) if b == a),
        telemetry_gaps=telemetry_gaps, lifecycle_gap_count=len(lifecycle_gaps),
        lifecycle_gaps=lifecycle_gaps[:8], lifecycle_rejected=lifecycle_rejected,
        lifecycle_null_id_removals=lifecycle_null_id,
        damage_gap_count=len(damage_gaps), damage_gaps=damage_gaps[:8],
        damage_sequences={str(k): v for k, v in damage_sequence.items()},
        damage_sources={str(k): round(v, 1) for k, v in damage_sources.items()},
        generation_count=len(generations),
        generation_reuse=sorted(k for k, v in generations.items() if len(v) > 1),
        kind_transitions=sorted(k for k, v in event_kinds.items() if len(v) > 1),
        duplicate_registrations=sum(1 for v in duplicate_registrations.values() if v > 1),
        effects_without_lineage=effects_without_lineage, units_without_lineage=units_without_lineage,
    )


def _binding(facts, contract, dataset_dir, scope, extra=None):
    record = dict(raw_capture_sha256=facts['raw_sha256'], raw_report_sha256=facts['report_sha256'],
                  bundle_manifest_sha=digest(Path(facts['bundle_manifest_path'])),
                  capture_code_sha256=facts['episode'].get('capture_code_sha256'),
                  contract_sha256=contract['sha256'],
                  dataset_manifest_sha=digest(Path(dataset_dir) / 'manifest.json'),
                  verification_scope=scope)
    if extra:
        record.update(extra)
    return record


def verify_raw_checks(facts, contract, dataset_dir, bundle_manifest_path) -> dict:
    bundle = json.loads(Path(bundle_manifest_path).read_text(encoding='utf-8'))
    worker = {entry['name']: entry['sha256'] for entry in bundle.get('worker_files', ())}
    identity = facts['identity']
    identity_ok = bool(
        bundle.get('libg_sha256') == identity.get('libg_sha256')
        and worker.get('libg.so') == identity.get('libg_sha256')
        and worker.get('lifecycle-probe.jar') == identity.get('host_sha256')
        and worker.get('libnative_host_bridge.so') == identity.get('bridge_sha256')
        and identity.get('elite_telemetry') == 'x86-v1'
    )
    # ruleset_resolved: the executed payload must agree with the authoritative
    # processing input and with the compiled plan, and must not be the template
    # default the diagnostics path silently inherits.
    episode = facts['episode']
    replay_battle = ((episode.get('replay') or {}).get('battle') or {})
    processing = facts['processing'] or {}
    plan = json.loads((Path(facts['capture_dir']) / 'plan.json').read_text(encoding='utf-8')) \
        if Path(facts['capture_dir'], 'plan.json').is_file() else {}
    template_path = Path(__file__).resolve().parents[1] / 'examples' / 'eight-card-bootstrap.json'
    template = json.loads(template_path.read_text(encoding='utf-8'))['battle']
    observed = dict(gamemode=replay_battle.get('gamemode'),
                    king_level=(replay_battle.get('avatar0') or {}).get('kt'))
    expected = dict(gamemode=processing.get('native_execution_game_mode_id'),
                    plan_gamemode=plan.get('native_execution_game_mode_id'))
    template_default = dict(gamemode=template.get('gamemode'),
                            king_level=(template.get('avatar0') or {}).get('kt'))
    agreements = dict(processing_input=observed['gamemode'] == expected['gamemode'],
                      compiled_plan=observed['gamemode'] == expected['plan_gamemode'],
                      not_template_default=(observed['gamemode'], observed['king_level'])
                      != (template_default['gamemode'], template_default['king_level']))
    ruleset_ok = bool(episode.get('capture_mode') == 'production_processing_contract'
                      and episode.get('native_replay_ready') is True and processing
                      and plan.get('native_replay_ready') is True
                      and plan.get('replay_tier') == 'native_replay_candidate'
                      and all(agreements.values()))
    continuous_ok = bool(facts['telemetry_gaps'] == 0 and facts['lifecycle_gap_count'] == 0
                         and facts['damage_gap_count'] == 0 and facts['lifecycle_rejected'] == 0)
    manifest_path = Path(dataset_dir) / 'manifest.json'
    manifest = json.loads(manifest_path.read_text(encoding='utf-8')) if manifest_path.is_file() else {}
    source = manifest.get('source')
    source_path = Path(source['path']) if source else None
    source_ok = bool(source and source_path.is_file() and digest(source_path) == source['sha256'])
    report = facts['report']
    opening_ok = ((report.get('opening_calibration') or {}).get('both_cycles_compatible') is True)
    return {
        'source_hashes': dict(passed=bool(source_ok), source=source,
                              observed=digest(source_path) if source_path and source_path.is_file() else None),
        'native_identity': dict(passed=identity_ok, observed=identity, expected=bundle.get('libg_sha256'),
                                worker_files={name: worker.get(name) for name in
                                              ('libg.so', 'lifecycle-probe.jar', 'libnative_host_bridge.so')}),
        'ruleset_resolved': dict(passed=ruleset_ok, capture_mode=episode.get('capture_mode'),
                                 native_replay_ready=episode.get('native_replay_ready'),
                                 replay_tier=episode.get('replay_tier'), observed=observed, expected=expected,
                                 processing_input_sha256=facts['processing_sha256']),
        'opening_cycle_compatible': dict(passed=opening_ok, opening_calibration=report.get('opening_calibration')),
        'tick_zero_capture': dict(passed=facts['first_tick'] == 0, first_tick=facts['first_tick']),
        'continuous_frames': dict(passed=facts['frame_gaps'] == 0, frames=facts['frame_count'],
                                  first_tick=facts['first_tick'], last_tick=facts['last_tick'],
                                  frame_gaps=facts['frame_gaps'], repeated_ticks=facts['repeated_ticks']),
        'continuous_events': dict(passed=continuous_ok, telemetry_gaps=facts['telemetry_gaps'],
                                  lifecycle_gap_count=facts['lifecycle_gap_count'],
                                  lifecycle_rejected=facts['lifecycle_rejected'],
                                  lifecycle_null_id_removals=facts['lifecycle_null_id_removals'],
                                  damage_gap_count=facts['damage_gap_count'],
                                  damage_sequences=facts['damage_sequences']),
        'entity_generation_identity': dict(passed=not facts['generation_reuse'],
                                           generation_count=facts['generation_count'],
                                           reused_keys=facts['generation_reuse'],
                                           multi_registration_keys=facts['duplicate_registrations']),
        'sequence_boundaries': dict(passed=not manifest.get('sequence_gaps'),
                                    sequence_gaps=manifest.get('sequence_gaps', []),
                                    shards=len(manifest.get('shards', [])),
                                    raw_truncated=manifest.get('raw_truncated')),
    }


def capability_certificates(facts, coverage, dataset_dir, contract, bundle_manifest_path) -> dict:
    coverage_path = Path(dataset_dir) / 'coverage.json'
    coverage_sha = digest(coverage_path)
    samples = coverage['actor_samples']
    counts = coverage['capability_sample_counts']
    scope = ('per-decision-sample capability verification over the whole capture; the capability must hold '
             'on every actor sample, recorded against the coverage report hash')
    certificates = {}
    for name in REQUIRED_CAPTURE:
        observed = int(counts.get(name, 0))
        passed = observed == samples and observed > 0
        record = dict(capability=name, verified_samples=observed, actor_samples=samples,
                      coverage_sha256=coverage_sha,
                      last_capability_failures=coverage.get('last_capability_failures', {}),
                      persistent_capture_failures=coverage.get('persistent_capture_failures', []),
                      observations=dict(coverage_file='coverage.json'))
        record.update(_binding(facts, contract, dataset_dir, scope))
        if name in ('groups', 'relations'):
            # Unknown lineage stays explicitly unknown: it must never inherit
            # another entity's deployment group. Groups are input feature banks
            # only, so an unknown lineage cannot fabricate a supervision label.
            record['lineage_unknown'] = dict(
                effects=len(facts['effects_without_lineage']), units=len(facts['units_without_lineage']),
                unit_keys=[row['key'] for row in facts['units_without_lineage'][:16]],
                effect_keys=[row['key'] for row in facts['effects_without_lineage'][:16]])
        record['status'] = 'passed' if passed else 'failed'
        certificates[name] = record
    return certificates


def strict_input_verification(dataset_dir, contract, device='cuda') -> dict:
    """Load every compiled sample through the official loader and run the strict
    batch contract on it: the input check for all actor samples."""
    dataset_dir = Path(dataset_dir).resolve()
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    if manifest.get('contract_sha256') != contract['sha256']:
        raise ValueError('compiled contract differs from current R0; recompile')
    config = ModelConfig()
    if config.allow_incomplete_capture:
        raise ValueError('diagnostic R0 cannot certify training data')
    from .input_validator import StrictInputValidator
    model = StrictInputValidator(config)
    samples = 0
    known_bits = 0
    sequences = 0
    labelled = 0
    for shard in manifest['shards']:
        path = (dataset_dir / shard['path']).resolve()
        if not path.is_relative_to(dataset_dir):
            raise ValueError('shard path outside dataset')
        sequence = load_sequence(path, expected_sha256=shard['sha256'])
        labelled += int(sequence.label_known.sum())
        for observation in sequence.observations:
            batch = observation.to(device)
            require_batch(batch, model)
            banks = (batch.semantic.elite.child, batch.semantic.elite.tower, batch.semantic.elite.groups,
                     batch.semantic.elite.own_cards, batch.semantic.elite.enemy_cards,
                     batch.semantic.elite.match, batch.semantic.elite.combat_features,
                     batch.semantic.elite.candidate_ability_features)
            for bank in banks:
                known = bank[..., 1::2]
                if not ((known == 0) | (known == 1)).all():
                    raise ValueError('invalid feature known bits')
                known_bits += int(known.numel())
            samples += 1
        sequences += 1
    coverage = json.loads((dataset_dir / 'coverage.json').read_text(encoding='utf-8'))
    # Samples whose capture streams were incomplete are excluded at compile time,
    # because the strict model refuses a batch containing one. The loader must
    # read exactly the retained samples, and the excluded ones must be accounted
    # for by reason: neither may be silently dropped.
    expected_samples = coverage.get('retained_samples', coverage['actor_samples'])
    if samples != expected_samples:
        raise ValueError(f'loader read {samples} samples but the coverage report accounts for {expected_samples} retained')
    excluded = int(coverage.get('excluded_samples', 0))
    if coverage['actor_samples'] != expected_samples + excluded:
        raise ValueError('excluded sample accounting does not add up to the actor samples')
    if excluded and not coverage.get('exclusion_reasons'):
        raise ValueError('excluded samples were not attributed to a reason')
    return dict(passed=samples > 0, samples=samples, expected_samples=expected_samples,
                actor_samples=coverage['actor_samples'], excluded_samples=excluded,
                exclusion_reasons=coverage.get('exclusion_reasons', {}), shards=sequences,
                known_bits_checked=known_bits, labelled_decisions=labelled,
                allowance='strict model, allow_incomplete_capture=False')


def digest_batch(batch) -> str:
    digest_ = hashlib.sha256()
    for name in ('entity_features', 'entity_positions', 'grid'):
        tensor = getattr(batch, name, None)
        if tensor is not None:
            digest_.update(name.encode())
            digest_.update(tensor.detach().cpu().contiguous().numpy().tobytes())
    for bank in ('child', 'tower', 'groups', 'match', 'combat_features'):
        tensor = getattr(batch.semantic.elite, bank, None)
        if tensor is not None:
            digest_.update(bank.encode())
            digest_.update(tensor.detach().cpu().contiguous().numpy().tobytes())
    return digest_.hexdigest()


def causality_check(dataset_dir, contract, *, include_tick, sequence_steps=16) -> dict:
    """public_information_only: truncating the raw stream after `include_tick` must
    leave every earlier decision sample byte-identical. A changed sample would
    mean it consumed information that did not exist at its own Tick."""
    from .r0_compile import compile_capture
    dataset_dir = Path(dataset_dir).resolve()
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    source = Path(manifest['source']['path'])
    temporary = Path(tempfile.mkdtemp(prefix='r0-causality-'))
    try:
        truncated = temporary / 'truncated'
        compile_capture(Path(manifest['raw_capture']['path']).parent, truncated,
                        sequence_steps=sequence_steps, source=source, max_tick=include_tick)
        cut_manifest = json.loads((truncated / 'manifest.json').read_text(encoding='utf-8'))
        cutoff = include_tick - DECISION_TICKS

        def index(root, entries):
            table = {}
            for shard in entries:
                sequence = load_sequence((root / shard['path']).resolve(), expected_sha256=shard['sha256'])
                for observation in sequence.observations:
                    if observation.ticks[0] < cutoff:
                        table[(observation.sides[0], observation.ticks[0])] = digest_batch(observation)
            return table

        full = index(dataset_dir, manifest['shards'])
        cut = index(truncated, cut_manifest['shards'])
        compared = sorted(set(full) & set(cut))
        changed = [key for key in compared if full[key] != cut[key]]
        return dict(passed=bool(compared) and not changed, compared_samples=len(compared),
                    changed_samples=[[side, tick] for side, tick in changed[:16]],
                    truncation_tick=include_tick, cutoff_tick=cutoff,
                    scope=f'all decision samples with tick < {cutoff} compared against a compile of the same '
                          f'stream truncated at tick {include_tick}')
    finally:
        shutil.rmtree(temporary, ignore_errors=True)


def nearest_action_bearing(dataset_dir, side, tick):
    """Nearest decision with an expert action target on each side of `tick`, so the
    evidence states exactly which region could carry a gradient."""
    dataset_dir = Path(dataset_dir).resolve()
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    before = after = None
    for shard in sorted((s for s in manifest['shards'] if s['side'] == side), key=lambda s: s['first_tick']):
        sequence = load_sequence((dataset_dir / shard['path']).resolve(), expected_sha256=shard['sha256'])
        for observation, action in zip(sequence.observations, sequence.actions):
            if int(action.count[0]) <= 0:
                continue
            decision = observation.ticks[0]
            if decision < tick and (before is None or decision > before):
                before = decision
            if decision >= tick and (after is None or decision < after):
                after = decision
    return before, after


def strict_training_verification(dataset_dir, output_root, *, device='cuda', steps=16, tbptt_steps=2,
                                 include_tick=3055) -> dict:
    """Real backward pass and checkpoint restore over several windows. Every window
    keeps the recurrent state continuous from Tick 0, and the repair region is
    covered instead of only the opening decisions."""
    from .r0_training_smoke import run as smoke_run
    before, after = nearest_action_bearing(dataset_dir, 0, include_tick)
    windows = [('opening-side0', 0, None), ('opening-side1', 1, None),
               (f'repair-tick{include_tick}-side0', 0, include_tick)]
    reports = []
    for label, side, first_tick in windows:
        output = Path(output_root) / label
        if output.exists():
            shutil.rmtree(output)
        report = smoke_run(dataset_dir, output, device=device, side=side, steps=steps,
                           tbptt_steps=tbptt_steps, first_tick=first_tick)
        if report.get('status') != 'passed':
            raise ValueError(f'strict training verification failed for {label}: {report.get("error")}')
        reports.append(dict(window=label, side=side, requested_first_tick=first_tick,
                            burnin_decisions=report.get('burnin_decisions'),
                            first_training_tick=report.get('first_training_tick'),
                            last_training_tick=report.get('last_training_tick'),
                            metrics=report.get('metrics'), checks=report.get('checks'),
                            weights_before_sha256=report.get('weights_before_sha256'),
                            weights_after_sha256=report.get('weights_after_sha256'),
                            checkpoint=report.get('checkpoint')))
    coverage = dict(
        target_tick=include_tick,
        nearest_action_bearing_before=before, nearest_action_bearing_after=after,
        recurrent_continuity='every window replays its lane from Tick 0, so the recurrent state seen by the '
                             f'repair region at Tick {include_tick} is carried continuously',
        gradient_before_repair=[r['window'] for r in reports if (r['last_training_tick'] or 0) < include_tick],
        gradient_after_repair=[r['window'] for r in reports if (r['first_training_tick'] or 0) > include_tick],
        limitation='A gradient window literally containing the repair Tick is not available in this lane: the '
                   'nearest action-bearing decisions are at the ticks above, farther apart than one contiguous '
                   'window, so the repair Tick sits inside the recurrent burn-in instead.')
    return dict(windows=reports, window_count=len(reports), coverage=coverage)


def strict_action_verification(dataset_dir, capture_dir, contract, *, max_ticks: int = 0) -> dict:
    """Re-derive the action-label checks from the persisted artifacts.

    These five were bare ``True`` the compiler asserted about its own output. They
    are recomputed here from the stored shards and the raw command stream, so a
    truncated shard, a manifest that does not describe its shards, or a label the
    legality model would have refused is caught instead of being trusted.
    """
    from training_r0.actions import ShadowLegality, OFFSET_TICKS
    from training_r0.config import DECISION_TICKS
    from training_r0.il_dataset import load_sequence
    from .r0_compile import canonical_cell, compilation_end_tick, index_capture
    import torch

    dataset_dir = Path(dataset_dir).resolve()
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    if manifest.get('contract_sha256') != contract['sha256']:
        raise ValueError('compiled contract differs from current R0; recompile')
    capture_dir = Path(capture_dir)
    raw = capture_dir / 'native-frames.jsonl.zst'
    if not raw.exists():
        raw = capture_dir / 'native-frames.jsonl.gz'
    episode, commands_index, trace = index_capture(raw)
    scope = manifest.get('compiled_scope') or {}
    end_tick = compilation_end_tick(trace['last_tick'], scope.get('requested_max_tick'))
    if max_ticks:
        end_tick = min(end_tick, max_ticks)
    bad_ticks = trace['bad_ticks']

    problems: list[str] = []
    shards = manifest['shards']
    partitions = {shard.get('partition') for shard in shards}
    battles = {shard.get('battle_uid') for shard in shards}
    battle_level_split = bool(shards) and len(partitions) == 1 and len(battles) == 1 and \
        partitions <= {'train', 'validation', 'test'}
    if not battle_level_split:
        problems.append(f'battle split inconsistent: partitions={sorted(partitions)} battles={len(battles)}')

    readback_failures: list[str] = []
    samples = 0
    labelled = 0
    cited = 0
    wait_labels = 0
    accounted_mismatch = 0
    for shard in shards:
        path = (dataset_dir / shard['path']).resolve()
        if not path.is_relative_to(dataset_dir):
            readback_failures.append(f'{shard["path"]}: outside dataset')
            continue
        # The loader verifies the recorded SHA256, so a shard that does not match
        # its manifest entry cannot be read silently.
        sequence = load_sequence(path, expected_sha256=shard['sha256'])
        ticks = [int(observation.ticks[0]) for observation in sequence.observations]
        if len(sequence.observations) != shard['steps']:
            readback_failures.append(f'{shard["path"]}: steps {len(sequence.observations)} != {shard["steps"]}')
        if ticks and (ticks[0] != shard['first_tick'] or ticks[-1] != shard['last_tick']):
            readback_failures.append(f'{shard["path"]}: ticks {ticks[0]}..{ticks[-1]} != '
                                     f'{shard["first_tick"]}..{shard["last_tick"]}')
        if int(sequence.label_known.sum()) != shard['known_labels']:
            readback_failures.append(f'{shard["path"]}: known labels {int(sequence.label_known.sum())} '
                                     f'!= {shard["known_labels"]}')
        if bool(sequence.starts_episode) != bool(shard['starts_episode']):
            readback_failures.append(f'{shard["path"]}: starts_episode mismatch')
        for step, observation in enumerate(sequence.observations):
            batch = observation.to('cpu')
            action = sequence.actions[step]
            tick = int(batch.ticks[0])
            side = int(batch.sides[0])
            samples += 1
            # Sentinels, micro-action count, delay range, monotone delays and target
            # range are all re-checked on the stored tensors.
            try:
                action.validate(1)
            except ValueError as error:
                problems.append(f'{shard["path"]}@{tick}: invalid action sequence: {error}')
                continue
            for order in range(int(action.count[0])):
                if int(action.offset_bin[0, order]) not in OFFSET_TICKS:
                    problems.append(f'{shard["path"]}@{tick}: delay {int(action.offset_bin[0, order])} '
                                    f'is not a legal offset')
            commands = commands_index.get((tick, side), ())
            complete = tick + DECISION_TICKS <= end_tick and not any(tick <= t <= tick + DECISION_TICKS
                                                                    for t in bad_ticks)
            # Re-derive the compiler's labelling rule in full, including whether each
            # accepted expert command is representable at all: a command whose target
            # cannot be placed on the R0 grid, or whose delay or candidate is not
            # legal at that boundary, is masked and must carry no loss. A labelled
            # sample therefore means "representable", and an unlabelled one must have
            # a concrete reason.
            representable = True
            reason = None
            if not complete:
                representable, reason = False, 'incomplete_window'
            elif len(commands) > 2:
                representable, reason = False, 'more_than_two_actions'
            elif any(not c.accepted for c in commands):
                representable, reason = False, 'source_action_rejected_or_unresolved'
            else:
                probe = ShadowLegality(batch)
                for order, command in enumerate(commands):
                    # Named distinctly from the stored ActionSequence above: reusing
                    # `action` here shadowed it for the labelled-sample check below.
                    command_action = command.action or {}
                    kind = command_action.get('type', 'play')
                    uid = (command_action.get('deck_index') if kind == 'play'
                           else 10000000 + command_action.get('entity_id', -1) if kind == 'ability' else -1)
                    try:
                        target = (canonical_cell(command_action.get('x'), command_action.get('y'), command.side)
                                  if kind == 'play' else -1)
                    except ValueError as error:
                        representable, reason = False, f'unrepresentable:{error}'
                        break
                    if command.side != side or command.window != tick:
                        representable, reason = False, 'wrong_owner_or_window'
                        break
                    legal = (batch.candidate_uids[0] == uid) & probe.candidate_mask(order)[0]
                    if int(legal.sum()) != 1:
                        representable, reason = False, f'expert_candidate_unavailable:{uid}'
                        break
                    index = int(legal.nonzero()[0, 0])
                    selected = torch.tensor([index])
                    if bool(batch.grid_targets[0, index]) != (target >= 0):
                        representable, reason = False, 'target_mode_mismatch'
                        break
                    if target >= 0 and not bool(probe.placement(selected)[0, target]):
                        representable, reason = False, 'expert_target_illegal'
                        break
                    delay = command.execution_tick - 1 - tick
                    if delay not in OFFSET_TICKS or not bool(probe.offset_mask(order)[0, delay]):
                        representable, reason = False, 'expert_delay_illegal'
                        break
                    probe.apply(torch.tensor([True]), selected, torch.tensor([target]), torch.tensor([delay]))
            expected_known = bool(representable)
            known = bool(sequence.label_known[step][0])
            if known != expected_known:
                accounted_mismatch += 1
                if len(problems) < 24:
                    problems.append(f'{shard["path"]}@{tick} side{side}: label_known={known} but the raw window '
                                    f'has {len(commands)} commands (complete={complete}, '
                                    f'accepted={[c.accepted for c in commands]}, reason={reason})')
            if not known:
                continue
            labelled += 1
            if not commands:
                wait_labels += 1
            # Every labelled micro-action must be re-selectable and legal under the
            # shadow legality model at that decision boundary.
            shadow = ShadowLegality(batch)
            for order in range(int(action.count[0])):
                uid = int(action.candidate_uid[0, order])
                target = int(action.target_cell[0, order])
                delay = int(action.offset_bin[0, order])
                matches = (batch.candidate_uids[0] == uid) & shadow.candidate_mask(order)[0]
                if int(matches.sum()) != 1:
                    problems.append(f'{shard["path"]}@{tick}: labelled candidate {uid} '
                                    f'not uniquely legal at step {order}')
                    break
                index = int(matches.nonzero()[0, 0])
                selected = torch.tensor([index])
                if bool(batch.grid_targets[0, index]) != (target >= 0):
                    problems.append(f'{shard["path"]}@{tick}: labelled target mode mismatch for {uid}')
                    break
                if target >= 0 and not bool(shadow.placement(selected)[0, target]):
                    problems.append(f'{shard["path"]}@{tick}: labelled target cell {target} '
                                    f'not placeable for {uid}')
                    break
                if not bool(shadow.offset_mask(order)[0, delay]):
                    problems.append(f'{shard["path"]}@{tick}: labelled delay {delay} illegal at step {order}')
                    break
                shadow.apply(torch.tensor([True]), selected, torch.tensor([target]), torch.tensor([delay]))
                cited += 1

    counts = manifest.get('label_counts') or {}
    accounted = int(counts.get('action', 0)) + int(counts.get('observed_wait', 0))
    if accounted != labelled:
        problems.append(f'label accounting: manifest says {accounted} labelled, shards hold {labelled}')
    offsets_ok = not any('invalid action sequence' in p or 'is not a legal offset' in p for p in problems)
    alignment_ok = not any('not uniquely legal' in p or 'target mode mismatch' in p
                           or 'not placeable' in p or 'illegal at step' in p for p in problems)
    return dict(
        passed=bool(not problems and battle_level_split and not readback_failures),
        samples=samples, labelled_samples=labelled, cited_micro_actions=cited,
        observed_wait_labels=wait_labels, manifest_labelled=accounted,
        window_mismatches=accounted_mismatch, label_reasons=dict(counts),
        end_tick=end_tick, bad_ticks=len(bad_ticks), shards=len(shards), partitions=sorted(partitions),
        battle_level_split=battle_level_split, shard_readback=not readback_failures,
        readback_failures=readback_failures[:8], action_offsets=offsets_ok,
        legal_candidate_alignment=alignment_ok,
        rejected_action_loss_masks=bool(accounted == labelled and not accounted_mismatch),
        problems=problems[:16], problem_count=len(problems),
        scope='action labels re-derived from the stored shards and the raw command stream')


def certify(capture_dir, dataset_dir, bundle_manifest_path, *, device='cuda', include_tick=3055,
            sequence_steps=16, causality=True, strict_inputs=True, training=True, steps=16, tbptt_steps=2) -> dict:
    dataset_dir = Path(dataset_dir).resolve()
    capture_dir = Path(capture_dir).resolve()
    contract = current_contract()
    evidence_dir = dataset_dir / 'evidence'
    evidence_dir.mkdir(exist_ok=True)
    facts = stream_facts(capture_dir)
    facts['bundle_manifest_path'] = str(Path(bundle_manifest_path).resolve())
    coverage = json.loads((dataset_dir / 'coverage.json').read_text(encoding='utf-8'))
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    checks = dict(manifest['checks'])
    raw_checks = verify_raw_checks(facts, contract, dataset_dir, bundle_manifest_path)
    for name in ('source_hashes', 'native_identity', 'ruleset_resolved', 'opening_cycle_compatible',
                 'tick_zero_capture', 'continuous_frames', 'continuous_events', 'entity_generation_identity',
                 'sequence_boundaries'):
        checks[name] = bool(raw_checks[name]['passed'])
    raw_record = dict(raw_checks)
    raw_record.update(_binding(facts, contract, dataset_dir,
                               'raw stream identity, ruleset resolver, event continuity, generation identity, '
                               'source hash and opening cycle'))
    raw_path = evidence_dir / 'raw_stream.json'
    atomic_json(raw_path, raw_record)

    if strict_inputs:
        inputs = strict_input_verification(dataset_dir, contract, device=device)
        checks['feature_applicability_and_known_masks'] = bool(inputs['passed'])
        inputs.update(_binding(facts, contract, dataset_dir,
                               'official loader + strict batch contract over every compiled sample'))
        atomic_json(evidence_dir / 'strict_inputs.json', inputs)
    if causality:
        causal = causality_check(dataset_dir, contract, include_tick=include_tick, sequence_steps=sequence_steps)
        checks['public_information_only'] = bool(causal['passed'])
        causal.update(_binding(facts, contract, dataset_dir, causal.pop('scope')))
        atomic_json(evidence_dir / 'causality.json', causal)

    # The five checks the compiler used to assert about its own labels are re-derived
    # from the stored shards and the raw command stream.
    actions = strict_action_verification(dataset_dir, capture_dir, contract)
    for name in ('legal_candidate_alignment', 'rejected_action_loss_masks', 'action_offsets',
                 'battle_level_split', 'shard_readback'):
        checks[name] = bool(actions[name])
    actions.update(_binding(facts, contract, dataset_dir, actions.pop('scope')))
    atomic_json(evidence_dir / 'strict_actions.json', actions)

    certificates = capability_certificates(facts, coverage, dataset_dir, contract, bundle_manifest_path)
    for name, record in certificates.items():
        path = evidence_dir / f'capability-{name}.json'
        atomic_json(path, record)
        record['evidence_path'] = str(path.relative_to(dataset_dir))
        record['evidence_sha256'] = digest(path)

    manifest['checks'] = {name: bool(checks.get(name, False)) for name in CHECKS}
    manifest['check_provenance'] = {name: ('verified_by_r0_certify' if name in VERIFIED_BY_CERTIFY
                                           else 'compiler_assertion_pending_verification')
                                    for name in CHECKS}
    manifest['capture_certificates'] = certificates
    manifest['raw_evidence'] = dict(path=str(raw_path.relative_to(dataset_dir)), sha256=digest(raw_path))
    manifest['lineage_unknown'] = dict(count_effects=len(facts['effects_without_lineage']),
                                       count_units=len(facts['units_without_lineage']),
                                       effects=facts['effects_without_lineage'][:16],
                                       units=facts['units_without_lineage'][:16])
    if training:
        training = strict_training_verification(dataset_dir, dataset_dir.parent / (dataset_dir.name + '-strict'),
                                                device=device, steps=steps, tbptt_steps=tbptt_steps,
                                                include_tick=include_tick)
        training_path = evidence_dir / 'strict_training.json'
        record = dict(training)
        record.update(_binding(facts, contract, dataset_dir,
                               'real backward pass, optimizer update and checkpoint restore over windows whose '
                               'recurrent state stays continuous from Tick 0, including the repair region'))
        atomic_json(training_path, record)
        manifest['strict_forward_evidence'] = dict(path=str(training_path.relative_to(dataset_dir)),
                                                   sha256=digest(training_path))
        checks['strict_r0_forward'] = True
        manifest['checks']['strict_r0_forward'] = True

    pending = [name for name in CHECKS if not manifest['checks'][name]]
    manifest['source_stage'] = 'validated_raw_capture' if not pending else 'retained_raw_capture_pending_admission'
    manifest['admission_pending'] = pending
    manifest['admission_note'] = ('Checks marked verified_by_r0_certify were produced from the actual artifacts; '
                                  'checks marked compiler_assertion_pending_verification are still asserted by the '
                                  'compiler and must be converted or rejected before production admission.')
    atomic_json(dataset_dir / 'manifest.json', manifest)
    require_manifest(manifest, contract)
    require_dataset_files(dataset_dir, contract)
    manifest['admission'] = 'require_manifest and require_dataset_files accepted'
    atomic_json(dataset_dir / 'manifest.json', manifest)
    return manifest


def load_admitted_dataset(dataset_dir, *, contract=None, device='cuda', limit=None):
    """The official loading entry: verify the manifest, every certificate and every
    referenced byte, then load the shards and run the strict batch contract."""
    dataset_dir = Path(dataset_dir).resolve()
    contract = contract or current_contract()
    manifest = json.loads((dataset_dir / 'manifest.json').read_text(encoding='utf-8'))
    require_manifest(manifest, contract)
    require_dataset_files(dataset_dir, contract)
    config = ModelConfig()
    model = R0Policy(CardVocabulary.from_native(), config).to(device).eval()
    sequences = []
    for shard in sorted(manifest['shards'], key=lambda s: (s['side'], s['first_tick'])):
        if limit is not None and len(sequences) >= limit:
            break
        sequence = load_sequence((dataset_dir / shard['path']).resolve(), expected_sha256=shard['sha256'])
        for observation in sequence.observations:
            require_batch(observation.to(device), model)
        sequences.append(sequence)
    return manifest, sequences


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('capture', type=Path)
    parser.add_argument('--dataset', type=Path, required=True)
    parser.add_argument('--bundle-manifest', type=Path, required=True)
    parser.add_argument('--device', default='cuda')
    parser.add_argument('--include-tick', type=int, default=3055)
    parser.add_argument('--sequence-steps', type=int, default=16)
    parser.add_argument('--no-causality', action='store_true')
    parser.add_argument('--no-strict-inputs', action='store_true')
    parser.add_argument('--no-training', action='store_true')
    args = parser.parse_args()
    manifest = certify(args.capture, args.dataset, args.bundle_manifest, device=args.device,
                       include_tick=args.include_tick, sequence_steps=args.sequence_steps,
                       causality=not args.no_causality, strict_inputs=not args.no_strict_inputs,
                       training=not args.no_training)
    print(json.dumps({k: v for k, v in manifest.items()
                      if k not in ('shards', 'capture_certificates')}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
